version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build: .
    container_name: urlshortener-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redisdata:
